# CMake generated Testfile for 
# Source directory: /home/gregory/Compiler
# Build directory: /home/gregory/Compiler
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(graph_/home/gregory/Compiler/tests/examples/test_factorial "/home/gregory/Compiler/tests/examples/build_graph.sh" "/home/gregory/Compiler/tests/examples/test_factorial")
add_test(graph_/home/gregory/Compiler/tests/examples/test_linked_list "/home/gregory/Compiler/tests/examples/build_graph.sh" "/home/gregory/Compiler/tests/examples/test_linked_list")
add_test(graph_/home/gregory/Compiler/tests/examples/test_linsearch "/home/gregory/Compiler/tests/examples/build_graph.sh" "/home/gregory/Compiler/tests/examples/test_linsearch")
add_test(graph_/home/gregory/Compiler/tests/examples/test_quick_sort "/home/gregory/Compiler/tests/examples/build_graph.sh" "/home/gregory/Compiler/tests/examples/test_quick_sort")
add_test(graph_/home/gregory/Compiler/tests/examples/test_tree_visitor "/home/gregory/Compiler/tests/examples/build_graph.sh" "/home/gregory/Compiler/tests/examples/test_tree_visitor")
add_test(bad_/home/gregory/Compiler/tests/bad/lc-1.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/lc-1.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-001.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-001.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-002.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-002.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-003.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-003.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-004.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-004.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-005.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-005.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-006.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-006.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-007.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-007.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-008.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-008.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-009.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-009.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-010.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-010.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-011.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-011.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-012.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-012.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-013.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-013.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-014.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-014.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-015.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-015.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-11a.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-11a.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-13a.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-13a.java" "1")
add_test(bad_/home/gregory/Compiler/tests/bad/tc-2a.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/bad/tc-2a.java" "1")
add_test(good_/home/gregory/Compiler/tests/good/binary-search.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/good/binary-search.java" "0")
add_test(good_/home/gregory/Compiler/tests/good/binary-tree.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/good/binary-tree.java" "0")
add_test(good_/home/gregory/Compiler/tests/good/bubble-sort.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/good/bubble-sort.java" "0")
add_test(good_/home/gregory/Compiler/tests/good/factorial.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/good/factorial.java" "0")
add_test(good_/home/gregory/Compiler/tests/good/linear-search.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/good/linear-search.java" "0")
add_test(good_/home/gregory/Compiler/tests/good/linked-list.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/good/linked-list.java" "0")
add_test(good_/home/gregory/Compiler/tests/good/quick-sort.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/good/quick-sort.java" "0")
add_test(good_/home/gregory/Compiler/tests/good/tree-visitor.java "/home/gregory/Compiler/tests/test.sh" "/home/gregory/Compiler/tests/good/tree-visitor.java" "0")
