# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gregory/Compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gregory/Compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test

.PHONY : test/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gregory/Compiler/CMakeFiles /home/gregory/Compiler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gregory/Compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Compiler

# Build rule for target.
Compiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Compiler
.PHONY : Compiler

# fast build rule for target.
Compiler/fast:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/build
.PHONY : Compiler/fast

#=============================================================================
# Target rules for targets named ContinuousSubmit

# Build rule for target.
ContinuousSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousSubmit
.PHONY : ContinuousSubmit

# fast build rule for target.
ContinuousSubmit/fast:
	$(MAKE) -f CMakeFiles/ContinuousSubmit.dir/build.make CMakeFiles/ContinuousSubmit.dir/build
.PHONY : ContinuousSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousCoverage

# Build rule for target.
ContinuousCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousCoverage
.PHONY : ContinuousCoverage

# fast build rule for target.
ContinuousCoverage/fast:
	$(MAKE) -f CMakeFiles/ContinuousCoverage.dir/build.make CMakeFiles/ContinuousCoverage.dir/build
.PHONY : ContinuousCoverage/fast

#=============================================================================
# Target rules for targets named ContinuousTest

# Build rule for target.
ContinuousTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousTest
.PHONY : ContinuousTest

# fast build rule for target.
ContinuousTest/fast:
	$(MAKE) -f CMakeFiles/ContinuousTest.dir/build.make CMakeFiles/ContinuousTest.dir/build
.PHONY : ContinuousTest/fast

#=============================================================================
# Target rules for targets named ContinuousBuild

# Build rule for target.
ContinuousBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousBuild
.PHONY : ContinuousBuild

# fast build rule for target.
ContinuousBuild/fast:
	$(MAKE) -f CMakeFiles/ContinuousBuild.dir/build.make CMakeFiles/ContinuousBuild.dir/build
.PHONY : ContinuousBuild/fast

#=============================================================================
# Target rules for targets named ContinuousMemCheck

# Build rule for target.
ContinuousMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousMemCheck
.PHONY : ContinuousMemCheck

# fast build rule for target.
ContinuousMemCheck/fast:
	$(MAKE) -f CMakeFiles/ContinuousMemCheck.dir/build.make CMakeFiles/ContinuousMemCheck.dir/build
.PHONY : ContinuousMemCheck/fast

#=============================================================================
# Target rules for targets named Nightly

# Build rule for target.
Nightly: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Nightly
.PHONY : Nightly

# fast build rule for target.
Nightly/fast:
	$(MAKE) -f CMakeFiles/Nightly.dir/build.make CMakeFiles/Nightly.dir/build
.PHONY : Nightly/fast

#=============================================================================
# Target rules for targets named NightlyTest

# Build rule for target.
NightlyTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyTest
.PHONY : NightlyTest

# fast build rule for target.
NightlyTest/fast:
	$(MAKE) -f CMakeFiles/NightlyTest.dir/build.make CMakeFiles/NightlyTest.dir/build
.PHONY : NightlyTest/fast

#=============================================================================
# Target rules for targets named NightlyUpdate

# Build rule for target.
NightlyUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyUpdate
.PHONY : NightlyUpdate

# fast build rule for target.
NightlyUpdate/fast:
	$(MAKE) -f CMakeFiles/NightlyUpdate.dir/build.make CMakeFiles/NightlyUpdate.dir/build
.PHONY : NightlyUpdate/fast

#=============================================================================
# Target rules for targets named Continuous

# Build rule for target.
Continuous: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Continuous
.PHONY : Continuous

# fast build rule for target.
Continuous/fast:
	$(MAKE) -f CMakeFiles/Continuous.dir/build.make CMakeFiles/Continuous.dir/build
.PHONY : Continuous/fast

#=============================================================================
# Target rules for targets named memcheck

# Build rule for target.
memcheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 memcheck
.PHONY : memcheck

# fast build rule for target.
memcheck/fast:
	$(MAKE) -f CMakeFiles/memcheck.dir/build.make CMakeFiles/memcheck.dir/build
.PHONY : memcheck/fast

#=============================================================================
# Target rules for targets named NightlyBuild

# Build rule for target.
NightlyBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyBuild
.PHONY : NightlyBuild

# fast build rule for target.
NightlyBuild/fast:
	$(MAKE) -f CMakeFiles/NightlyBuild.dir/build.make CMakeFiles/NightlyBuild.dir/build
.PHONY : NightlyBuild/fast

#=============================================================================
# Target rules for targets named NightlyStart

# Build rule for target.
NightlyStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyStart
.PHONY : NightlyStart

# fast build rule for target.
NightlyStart/fast:
	$(MAKE) -f CMakeFiles/NightlyStart.dir/build.make CMakeFiles/NightlyStart.dir/build
.PHONY : NightlyStart/fast

#=============================================================================
# Target rules for targets named NightlyMemoryCheck

# Build rule for target.
NightlyMemoryCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemoryCheck
.PHONY : NightlyMemoryCheck

# fast build rule for target.
NightlyMemoryCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemoryCheck.dir/build.make CMakeFiles/NightlyMemoryCheck.dir/build
.PHONY : NightlyMemoryCheck/fast

#=============================================================================
# Target rules for targets named NightlyMemCheck

# Build rule for target.
NightlyMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyMemCheck
.PHONY : NightlyMemCheck

# fast build rule for target.
NightlyMemCheck/fast:
	$(MAKE) -f CMakeFiles/NightlyMemCheck.dir/build.make CMakeFiles/NightlyMemCheck.dir/build
.PHONY : NightlyMemCheck/fast

#=============================================================================
# Target rules for targets named ExperimentalStart

# Build rule for target.
ExperimentalStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalStart
.PHONY : ExperimentalStart

# fast build rule for target.
ExperimentalStart/fast:
	$(MAKE) -f CMakeFiles/ExperimentalStart.dir/build.make CMakeFiles/ExperimentalStart.dir/build
.PHONY : ExperimentalStart/fast

#=============================================================================
# Target rules for targets named ContinuousConfigure

# Build rule for target.
ContinuousConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousConfigure
.PHONY : ContinuousConfigure

# fast build rule for target.
ContinuousConfigure/fast:
	$(MAKE) -f CMakeFiles/ContinuousConfigure.dir/build.make CMakeFiles/ContinuousConfigure.dir/build
.PHONY : ContinuousConfigure/fast

#=============================================================================
# Target rules for targets named NightlyCoverage

# Build rule for target.
NightlyCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyCoverage
.PHONY : NightlyCoverage

# fast build rule for target.
NightlyCoverage/fast:
	$(MAKE) -f CMakeFiles/NightlyCoverage.dir/build.make CMakeFiles/NightlyCoverage.dir/build
.PHONY : NightlyCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalUpdate

# Build rule for target.
ExperimentalUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalUpdate
.PHONY : ExperimentalUpdate

# fast build rule for target.
ExperimentalUpdate/fast:
	$(MAKE) -f CMakeFiles/ExperimentalUpdate.dir/build.make CMakeFiles/ExperimentalUpdate.dir/build
.PHONY : ExperimentalUpdate/fast

#=============================================================================
# Target rules for targets named ExperimentalConfigure

# Build rule for target.
ExperimentalConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalConfigure
.PHONY : ExperimentalConfigure

# fast build rule for target.
ExperimentalConfigure/fast:
	$(MAKE) -f CMakeFiles/ExperimentalConfigure.dir/build.make CMakeFiles/ExperimentalConfigure.dir/build
.PHONY : ExperimentalConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalCoverage

# Build rule for target.
ExperimentalCoverage: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalCoverage
.PHONY : ExperimentalCoverage

# fast build rule for target.
ExperimentalCoverage/fast:
	$(MAKE) -f CMakeFiles/ExperimentalCoverage.dir/build.make CMakeFiles/ExperimentalCoverage.dir/build
.PHONY : ExperimentalCoverage/fast

#=============================================================================
# Target rules for targets named ExperimentalBuild

# Build rule for target.
ExperimentalBuild: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalBuild
.PHONY : ExperimentalBuild

# fast build rule for target.
ExperimentalBuild/fast:
	$(MAKE) -f CMakeFiles/ExperimentalBuild.dir/build.make CMakeFiles/ExperimentalBuild.dir/build
.PHONY : ExperimentalBuild/fast

#=============================================================================
# Target rules for targets named NightlyConfigure

# Build rule for target.
NightlyConfigure: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlyConfigure
.PHONY : NightlyConfigure

# fast build rule for target.
NightlyConfigure/fast:
	$(MAKE) -f CMakeFiles/NightlyConfigure.dir/build.make CMakeFiles/NightlyConfigure.dir/build
.PHONY : NightlyConfigure/fast

#=============================================================================
# Target rules for targets named ExperimentalTest

# Build rule for target.
ExperimentalTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalTest
.PHONY : ExperimentalTest

# fast build rule for target.
ExperimentalTest/fast:
	$(MAKE) -f CMakeFiles/ExperimentalTest.dir/build.make CMakeFiles/ExperimentalTest.dir/build
.PHONY : ExperimentalTest/fast

#=============================================================================
# Target rules for targets named ExperimentalMemCheck

# Build rule for target.
ExperimentalMemCheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalMemCheck
.PHONY : ExperimentalMemCheck

# fast build rule for target.
ExperimentalMemCheck/fast:
	$(MAKE) -f CMakeFiles/ExperimentalMemCheck.dir/build.make CMakeFiles/ExperimentalMemCheck.dir/build
.PHONY : ExperimentalMemCheck/fast

#=============================================================================
# Target rules for targets named cppcheck

# Build rule for target.
cppcheck: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 cppcheck
.PHONY : cppcheck

# fast build rule for target.
cppcheck/fast:
	$(MAKE) -f CMakeFiles/cppcheck.dir/build.make CMakeFiles/cppcheck.dir/build
.PHONY : cppcheck/fast

#=============================================================================
# Target rules for targets named Experimental

# Build rule for target.
Experimental: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Experimental
.PHONY : Experimental

# fast build rule for target.
Experimental/fast:
	$(MAKE) -f CMakeFiles/Experimental.dir/build.make CMakeFiles/Experimental.dir/build
.PHONY : Experimental/fast

#=============================================================================
# Target rules for targets named NightlySubmit

# Build rule for target.
NightlySubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 NightlySubmit
.PHONY : NightlySubmit

# fast build rule for target.
NightlySubmit/fast:
	$(MAKE) -f CMakeFiles/NightlySubmit.dir/build.make CMakeFiles/NightlySubmit.dir/build
.PHONY : NightlySubmit/fast

#=============================================================================
# Target rules for targets named ExperimentalSubmit

# Build rule for target.
ExperimentalSubmit: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ExperimentalSubmit
.PHONY : ExperimentalSubmit

# fast build rule for target.
ExperimentalSubmit/fast:
	$(MAKE) -f CMakeFiles/ExperimentalSubmit.dir/build.make CMakeFiles/ExperimentalSubmit.dir/build
.PHONY : ExperimentalSubmit/fast

#=============================================================================
# Target rules for targets named ContinuousStart

# Build rule for target.
ContinuousStart: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousStart
.PHONY : ContinuousStart

# fast build rule for target.
ContinuousStart/fast:
	$(MAKE) -f CMakeFiles/ContinuousStart.dir/build.make CMakeFiles/ContinuousStart.dir/build
.PHONY : ContinuousStart/fast

#=============================================================================
# Target rules for targets named ContinuousUpdate

# Build rule for target.
ContinuousUpdate: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ContinuousUpdate
.PHONY : ContinuousUpdate

# fast build rule for target.
ContinuousUpdate/fast:
	$(MAKE) -f CMakeFiles/ContinuousUpdate.dir/build.make CMakeFiles/ContinuousUpdate.dir/build
.PHONY : ContinuousUpdate/fast

lexer.o: lexer.cpp.o

.PHONY : lexer.o

# target to build an object file
lexer.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer.cpp.o
.PHONY : lexer.cpp.o

lexer.i: lexer.cpp.i

.PHONY : lexer.i

# target to preprocess a source file
lexer.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer.cpp.i
.PHONY : lexer.cpp.i

lexer.s: lexer.cpp.s

.PHONY : lexer.s

# target to generate assembly for a file
lexer.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer.cpp.s
.PHONY : lexer.cpp.s

parser.o: parser.cpp.o

.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i

.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s

.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser.cpp.s
.PHONY : parser.cpp.s

src/AST/ASTPrinter.o: src/AST/ASTPrinter.cpp.o

.PHONY : src/AST/ASTPrinter.o

# target to build an object file
src/AST/ASTPrinter.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/AST/ASTPrinter.cpp.o
.PHONY : src/AST/ASTPrinter.cpp.o

src/AST/ASTPrinter.i: src/AST/ASTPrinter.cpp.i

.PHONY : src/AST/ASTPrinter.i

# target to preprocess a source file
src/AST/ASTPrinter.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/AST/ASTPrinter.cpp.i
.PHONY : src/AST/ASTPrinter.cpp.i

src/AST/ASTPrinter.s: src/AST/ASTPrinter.cpp.s

.PHONY : src/AST/ASTPrinter.s

# target to generate assembly for a file
src/AST/ASTPrinter.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/AST/ASTPrinter.cpp.s
.PHONY : src/AST/ASTPrinter.cpp.s

src/ErrorStorage/ErrorStorage.o: src/ErrorStorage/ErrorStorage.cpp.o

.PHONY : src/ErrorStorage/ErrorStorage.o

# target to build an object file
src/ErrorStorage/ErrorStorage.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/ErrorStorage/ErrorStorage.cpp.o
.PHONY : src/ErrorStorage/ErrorStorage.cpp.o

src/ErrorStorage/ErrorStorage.i: src/ErrorStorage/ErrorStorage.cpp.i

.PHONY : src/ErrorStorage/ErrorStorage.i

# target to preprocess a source file
src/ErrorStorage/ErrorStorage.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/ErrorStorage/ErrorStorage.cpp.i
.PHONY : src/ErrorStorage/ErrorStorage.cpp.i

src/ErrorStorage/ErrorStorage.s: src/ErrorStorage/ErrorStorage.cpp.s

.PHONY : src/ErrorStorage/ErrorStorage.s

# target to generate assembly for a file
src/ErrorStorage/ErrorStorage.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/ErrorStorage/ErrorStorage.cpp.s
.PHONY : src/ErrorStorage/ErrorStorage.cpp.s

src/IRT/Expression.o: src/IRT/Expression.cpp.o

.PHONY : src/IRT/Expression.o

# target to build an object file
src/IRT/Expression.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Expression.cpp.o
.PHONY : src/IRT/Expression.cpp.o

src/IRT/Expression.i: src/IRT/Expression.cpp.i

.PHONY : src/IRT/Expression.i

# target to preprocess a source file
src/IRT/Expression.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Expression.cpp.i
.PHONY : src/IRT/Expression.cpp.i

src/IRT/Expression.s: src/IRT/Expression.cpp.s

.PHONY : src/IRT/Expression.s

# target to generate assembly for a file
src/IRT/Expression.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Expression.cpp.s
.PHONY : src/IRT/Expression.cpp.s

src/IRT/Frame.o: src/IRT/Frame.cpp.o

.PHONY : src/IRT/Frame.o

# target to build an object file
src/IRT/Frame.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Frame.cpp.o
.PHONY : src/IRT/Frame.cpp.o

src/IRT/Frame.i: src/IRT/Frame.cpp.i

.PHONY : src/IRT/Frame.i

# target to preprocess a source file
src/IRT/Frame.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Frame.cpp.i
.PHONY : src/IRT/Frame.cpp.i

src/IRT/Frame.s: src/IRT/Frame.cpp.s

.PHONY : src/IRT/Frame.s

# target to generate assembly for a file
src/IRT/Frame.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Frame.cpp.s
.PHONY : src/IRT/Frame.cpp.s

src/IRT/IRTreePrinter.o: src/IRT/IRTreePrinter.cpp.o

.PHONY : src/IRT/IRTreePrinter.o

# target to build an object file
src/IRT/IRTreePrinter.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/IRTreePrinter.cpp.o
.PHONY : src/IRT/IRTreePrinter.cpp.o

src/IRT/IRTreePrinter.i: src/IRT/IRTreePrinter.cpp.i

.PHONY : src/IRT/IRTreePrinter.i

# target to preprocess a source file
src/IRT/IRTreePrinter.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/IRTreePrinter.cpp.i
.PHONY : src/IRT/IRTreePrinter.cpp.i

src/IRT/IRTreePrinter.s: src/IRT/IRTreePrinter.cpp.s

.PHONY : src/IRT/IRTreePrinter.s

# target to generate assembly for a file
src/IRT/IRTreePrinter.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/IRTreePrinter.cpp.s
.PHONY : src/IRT/IRTreePrinter.cpp.s

src/IRT/Label.o: src/IRT/Label.cpp.o

.PHONY : src/IRT/Label.o

# target to build an object file
src/IRT/Label.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Label.cpp.o
.PHONY : src/IRT/Label.cpp.o

src/IRT/Label.i: src/IRT/Label.cpp.i

.PHONY : src/IRT/Label.i

# target to preprocess a source file
src/IRT/Label.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Label.cpp.i
.PHONY : src/IRT/Label.cpp.i

src/IRT/Label.s: src/IRT/Label.cpp.s

.PHONY : src/IRT/Label.s

# target to generate assembly for a file
src/IRT/Label.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Label.cpp.s
.PHONY : src/IRT/Label.cpp.s

src/IRT/Statement.o: src/IRT/Statement.cpp.o

.PHONY : src/IRT/Statement.o

# target to build an object file
src/IRT/Statement.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Statement.cpp.o
.PHONY : src/IRT/Statement.cpp.o

src/IRT/Statement.i: src/IRT/Statement.cpp.i

.PHONY : src/IRT/Statement.i

# target to preprocess a source file
src/IRT/Statement.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Statement.cpp.i
.PHONY : src/IRT/Statement.cpp.i

src/IRT/Statement.s: src/IRT/Statement.cpp.s

.PHONY : src/IRT/Statement.s

# target to generate assembly for a file
src/IRT/Statement.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Statement.cpp.s
.PHONY : src/IRT/Statement.cpp.s

src/IRT/Translator.o: src/IRT/Translator.cpp.o

.PHONY : src/IRT/Translator.o

# target to build an object file
src/IRT/Translator.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Translator.cpp.o
.PHONY : src/IRT/Translator.cpp.o

src/IRT/Translator.i: src/IRT/Translator.cpp.i

.PHONY : src/IRT/Translator.i

# target to preprocess a source file
src/IRT/Translator.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Translator.cpp.i
.PHONY : src/IRT/Translator.cpp.i

src/IRT/Translator.s: src/IRT/Translator.cpp.s

.PHONY : src/IRT/Translator.s

# target to generate assembly for a file
src/IRT/Translator.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Translator.cpp.s
.PHONY : src/IRT/Translator.cpp.s

src/Location/Location.o: src/Location/Location.cpp.o

.PHONY : src/Location/Location.o

# target to build an object file
src/Location/Location.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/Location/Location.cpp.o
.PHONY : src/Location/Location.cpp.o

src/Location/Location.i: src/Location/Location.cpp.i

.PHONY : src/Location/Location.i

# target to preprocess a source file
src/Location/Location.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/Location/Location.cpp.i
.PHONY : src/Location/Location.cpp.i

src/Location/Location.s: src/Location/Location.cpp.s

.PHONY : src/Location/Location.s

# target to generate assembly for a file
src/Location/Location.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/Location/Location.cpp.s
.PHONY : src/Location/Location.cpp.s

src/RuleClasses/Arg.o: src/RuleClasses/Arg.cpp.o

.PHONY : src/RuleClasses/Arg.o

# target to build an object file
src/RuleClasses/Arg.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Arg.cpp.o
.PHONY : src/RuleClasses/Arg.cpp.o

src/RuleClasses/Arg.i: src/RuleClasses/Arg.cpp.i

.PHONY : src/RuleClasses/Arg.i

# target to preprocess a source file
src/RuleClasses/Arg.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Arg.cpp.i
.PHONY : src/RuleClasses/Arg.cpp.i

src/RuleClasses/Arg.s: src/RuleClasses/Arg.cpp.s

.PHONY : src/RuleClasses/Arg.s

# target to generate assembly for a file
src/RuleClasses/Arg.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Arg.cpp.s
.PHONY : src/RuleClasses/Arg.cpp.s

src/RuleClasses/Class.o: src/RuleClasses/Class.cpp.o

.PHONY : src/RuleClasses/Class.o

# target to build an object file
src/RuleClasses/Class.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Class.cpp.o
.PHONY : src/RuleClasses/Class.cpp.o

src/RuleClasses/Class.i: src/RuleClasses/Class.cpp.i

.PHONY : src/RuleClasses/Class.i

# target to preprocess a source file
src/RuleClasses/Class.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Class.cpp.i
.PHONY : src/RuleClasses/Class.cpp.i

src/RuleClasses/Class.s: src/RuleClasses/Class.cpp.s

.PHONY : src/RuleClasses/Class.s

# target to generate assembly for a file
src/RuleClasses/Class.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Class.cpp.s
.PHONY : src/RuleClasses/Class.cpp.s

src/RuleClasses/Expression.o: src/RuleClasses/Expression.cpp.o

.PHONY : src/RuleClasses/Expression.o

# target to build an object file
src/RuleClasses/Expression.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Expression.cpp.o
.PHONY : src/RuleClasses/Expression.cpp.o

src/RuleClasses/Expression.i: src/RuleClasses/Expression.cpp.i

.PHONY : src/RuleClasses/Expression.i

# target to preprocess a source file
src/RuleClasses/Expression.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Expression.cpp.i
.PHONY : src/RuleClasses/Expression.cpp.i

src/RuleClasses/Expression.s: src/RuleClasses/Expression.cpp.s

.PHONY : src/RuleClasses/Expression.s

# target to generate assembly for a file
src/RuleClasses/Expression.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Expression.cpp.s
.PHONY : src/RuleClasses/Expression.cpp.s

src/RuleClasses/MainClass.o: src/RuleClasses/MainClass.cpp.o

.PHONY : src/RuleClasses/MainClass.o

# target to build an object file
src/RuleClasses/MainClass.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/MainClass.cpp.o
.PHONY : src/RuleClasses/MainClass.cpp.o

src/RuleClasses/MainClass.i: src/RuleClasses/MainClass.cpp.i

.PHONY : src/RuleClasses/MainClass.i

# target to preprocess a source file
src/RuleClasses/MainClass.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/MainClass.cpp.i
.PHONY : src/RuleClasses/MainClass.cpp.i

src/RuleClasses/MainClass.s: src/RuleClasses/MainClass.cpp.s

.PHONY : src/RuleClasses/MainClass.s

# target to generate assembly for a file
src/RuleClasses/MainClass.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/MainClass.cpp.s
.PHONY : src/RuleClasses/MainClass.cpp.s

src/RuleClasses/Method.o: src/RuleClasses/Method.cpp.o

.PHONY : src/RuleClasses/Method.o

# target to build an object file
src/RuleClasses/Method.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Method.cpp.o
.PHONY : src/RuleClasses/Method.cpp.o

src/RuleClasses/Method.i: src/RuleClasses/Method.cpp.i

.PHONY : src/RuleClasses/Method.i

# target to preprocess a source file
src/RuleClasses/Method.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Method.cpp.i
.PHONY : src/RuleClasses/Method.cpp.i

src/RuleClasses/Method.s: src/RuleClasses/Method.cpp.s

.PHONY : src/RuleClasses/Method.s

# target to generate assembly for a file
src/RuleClasses/Method.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Method.cpp.s
.PHONY : src/RuleClasses/Method.cpp.s

src/RuleClasses/Program.o: src/RuleClasses/Program.cpp.o

.PHONY : src/RuleClasses/Program.o

# target to build an object file
src/RuleClasses/Program.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Program.cpp.o
.PHONY : src/RuleClasses/Program.cpp.o

src/RuleClasses/Program.i: src/RuleClasses/Program.cpp.i

.PHONY : src/RuleClasses/Program.i

# target to preprocess a source file
src/RuleClasses/Program.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Program.cpp.i
.PHONY : src/RuleClasses/Program.cpp.i

src/RuleClasses/Program.s: src/RuleClasses/Program.cpp.s

.PHONY : src/RuleClasses/Program.s

# target to generate assembly for a file
src/RuleClasses/Program.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Program.cpp.s
.PHONY : src/RuleClasses/Program.cpp.s

src/RuleClasses/Statement.o: src/RuleClasses/Statement.cpp.o

.PHONY : src/RuleClasses/Statement.o

# target to build an object file
src/RuleClasses/Statement.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Statement.cpp.o
.PHONY : src/RuleClasses/Statement.cpp.o

src/RuleClasses/Statement.i: src/RuleClasses/Statement.cpp.i

.PHONY : src/RuleClasses/Statement.i

# target to preprocess a source file
src/RuleClasses/Statement.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Statement.cpp.i
.PHONY : src/RuleClasses/Statement.cpp.i

src/RuleClasses/Statement.s: src/RuleClasses/Statement.cpp.s

.PHONY : src/RuleClasses/Statement.s

# target to generate assembly for a file
src/RuleClasses/Statement.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Statement.cpp.s
.PHONY : src/RuleClasses/Statement.cpp.s

src/RuleClasses/Type.o: src/RuleClasses/Type.cpp.o

.PHONY : src/RuleClasses/Type.o

# target to build an object file
src/RuleClasses/Type.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Type.cpp.o
.PHONY : src/RuleClasses/Type.cpp.o

src/RuleClasses/Type.i: src/RuleClasses/Type.cpp.i

.PHONY : src/RuleClasses/Type.i

# target to preprocess a source file
src/RuleClasses/Type.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Type.cpp.i
.PHONY : src/RuleClasses/Type.cpp.i

src/RuleClasses/Type.s: src/RuleClasses/Type.cpp.s

.PHONY : src/RuleClasses/Type.s

# target to generate assembly for a file
src/RuleClasses/Type.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Type.cpp.s
.PHONY : src/RuleClasses/Type.cpp.s

src/RuleClasses/Var.o: src/RuleClasses/Var.cpp.o

.PHONY : src/RuleClasses/Var.o

# target to build an object file
src/RuleClasses/Var.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Var.cpp.o
.PHONY : src/RuleClasses/Var.cpp.o

src/RuleClasses/Var.i: src/RuleClasses/Var.cpp.i

.PHONY : src/RuleClasses/Var.i

# target to preprocess a source file
src/RuleClasses/Var.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Var.cpp.i
.PHONY : src/RuleClasses/Var.cpp.i

src/RuleClasses/Var.s: src/RuleClasses/Var.cpp.s

.PHONY : src/RuleClasses/Var.s

# target to generate assembly for a file
src/RuleClasses/Var.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Var.cpp.s
.PHONY : src/RuleClasses/Var.cpp.s

src/SymbolTable/Symbol.o: src/SymbolTable/Symbol.cpp.o

.PHONY : src/SymbolTable/Symbol.o

# target to build an object file
src/SymbolTable/Symbol.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/Symbol.cpp.o
.PHONY : src/SymbolTable/Symbol.cpp.o

src/SymbolTable/Symbol.i: src/SymbolTable/Symbol.cpp.i

.PHONY : src/SymbolTable/Symbol.i

# target to preprocess a source file
src/SymbolTable/Symbol.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/Symbol.cpp.i
.PHONY : src/SymbolTable/Symbol.cpp.i

src/SymbolTable/Symbol.s: src/SymbolTable/Symbol.cpp.s

.PHONY : src/SymbolTable/Symbol.s

# target to generate assembly for a file
src/SymbolTable/Symbol.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/Symbol.cpp.s
.PHONY : src/SymbolTable/Symbol.cpp.s

src/SymbolTable/SymbolTable.o: src/SymbolTable/SymbolTable.cpp.o

.PHONY : src/SymbolTable/SymbolTable.o

# target to build an object file
src/SymbolTable/SymbolTable.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/SymbolTable.cpp.o
.PHONY : src/SymbolTable/SymbolTable.cpp.o

src/SymbolTable/SymbolTable.i: src/SymbolTable/SymbolTable.cpp.i

.PHONY : src/SymbolTable/SymbolTable.i

# target to preprocess a source file
src/SymbolTable/SymbolTable.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/SymbolTable.cpp.i
.PHONY : src/SymbolTable/SymbolTable.cpp.i

src/SymbolTable/SymbolTable.s: src/SymbolTable/SymbolTable.cpp.s

.PHONY : src/SymbolTable/SymbolTable.s

# target to generate assembly for a file
src/SymbolTable/SymbolTable.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/SymbolTable.cpp.s
.PHONY : src/SymbolTable/SymbolTable.cpp.s

src/SymbolTable/SymbolTableBuilder.o: src/SymbolTable/SymbolTableBuilder.cpp.o

.PHONY : src/SymbolTable/SymbolTableBuilder.o

# target to build an object file
src/SymbolTable/SymbolTableBuilder.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/SymbolTableBuilder.cpp.o
.PHONY : src/SymbolTable/SymbolTableBuilder.cpp.o

src/SymbolTable/SymbolTableBuilder.i: src/SymbolTable/SymbolTableBuilder.cpp.i

.PHONY : src/SymbolTable/SymbolTableBuilder.i

# target to preprocess a source file
src/SymbolTable/SymbolTableBuilder.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/SymbolTableBuilder.cpp.i
.PHONY : src/SymbolTable/SymbolTableBuilder.cpp.i

src/SymbolTable/SymbolTableBuilder.s: src/SymbolTable/SymbolTableBuilder.cpp.s

.PHONY : src/SymbolTable/SymbolTableBuilder.s

# target to generate assembly for a file
src/SymbolTable/SymbolTableBuilder.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/SymbolTableBuilder.cpp.s
.PHONY : src/SymbolTable/SymbolTableBuilder.cpp.s

src/SymbolTable/TypeChecker.o: src/SymbolTable/TypeChecker.cpp.o

.PHONY : src/SymbolTable/TypeChecker.o

# target to build an object file
src/SymbolTable/TypeChecker.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/TypeChecker.cpp.o
.PHONY : src/SymbolTable/TypeChecker.cpp.o

src/SymbolTable/TypeChecker.i: src/SymbolTable/TypeChecker.cpp.i

.PHONY : src/SymbolTable/TypeChecker.i

# target to preprocess a source file
src/SymbolTable/TypeChecker.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/TypeChecker.cpp.i
.PHONY : src/SymbolTable/TypeChecker.cpp.i

src/SymbolTable/TypeChecker.s: src/SymbolTable/TypeChecker.cpp.s

.PHONY : src/SymbolTable/TypeChecker.s

# target to generate assembly for a file
src/SymbolTable/TypeChecker.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/TypeChecker.cpp.s
.PHONY : src/SymbolTable/TypeChecker.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Compiler"
	@echo "... ContinuousSubmit"
	@echo "... ContinuousCoverage"
	@echo "... ContinuousTest"
	@echo "... ContinuousBuild"
	@echo "... ContinuousMemCheck"
	@echo "... Nightly"
	@echo "... NightlyTest"
	@echo "... NightlyUpdate"
	@echo "... Continuous"
	@echo "... memcheck"
	@echo "... NightlyBuild"
	@echo "... NightlyStart"
	@echo "... NightlyMemoryCheck"
	@echo "... NightlyMemCheck"
	@echo "... ExperimentalStart"
	@echo "... ContinuousConfigure"
	@echo "... NightlyCoverage"
	@echo "... ExperimentalUpdate"
	@echo "... test"
	@echo "... ExperimentalConfigure"
	@echo "... ExperimentalCoverage"
	@echo "... ExperimentalBuild"
	@echo "... NightlyConfigure"
	@echo "... ExperimentalTest"
	@echo "... ExperimentalMemCheck"
	@echo "... cppcheck"
	@echo "... Experimental"
	@echo "... NightlySubmit"
	@echo "... ExperimentalSubmit"
	@echo "... ContinuousStart"
	@echo "... ContinuousUpdate"
	@echo "... lexer.o"
	@echo "... lexer.i"
	@echo "... lexer.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... src/AST/ASTPrinter.o"
	@echo "... src/AST/ASTPrinter.i"
	@echo "... src/AST/ASTPrinter.s"
	@echo "... src/ErrorStorage/ErrorStorage.o"
	@echo "... src/ErrorStorage/ErrorStorage.i"
	@echo "... src/ErrorStorage/ErrorStorage.s"
	@echo "... src/IRT/Expression.o"
	@echo "... src/IRT/Expression.i"
	@echo "... src/IRT/Expression.s"
	@echo "... src/IRT/Frame.o"
	@echo "... src/IRT/Frame.i"
	@echo "... src/IRT/Frame.s"
	@echo "... src/IRT/IRTreePrinter.o"
	@echo "... src/IRT/IRTreePrinter.i"
	@echo "... src/IRT/IRTreePrinter.s"
	@echo "... src/IRT/Label.o"
	@echo "... src/IRT/Label.i"
	@echo "... src/IRT/Label.s"
	@echo "... src/IRT/Statement.o"
	@echo "... src/IRT/Statement.i"
	@echo "... src/IRT/Statement.s"
	@echo "... src/IRT/Translator.o"
	@echo "... src/IRT/Translator.i"
	@echo "... src/IRT/Translator.s"
	@echo "... src/Location/Location.o"
	@echo "... src/Location/Location.i"
	@echo "... src/Location/Location.s"
	@echo "... src/RuleClasses/Arg.o"
	@echo "... src/RuleClasses/Arg.i"
	@echo "... src/RuleClasses/Arg.s"
	@echo "... src/RuleClasses/Class.o"
	@echo "... src/RuleClasses/Class.i"
	@echo "... src/RuleClasses/Class.s"
	@echo "... src/RuleClasses/Expression.o"
	@echo "... src/RuleClasses/Expression.i"
	@echo "... src/RuleClasses/Expression.s"
	@echo "... src/RuleClasses/MainClass.o"
	@echo "... src/RuleClasses/MainClass.i"
	@echo "... src/RuleClasses/MainClass.s"
	@echo "... src/RuleClasses/Method.o"
	@echo "... src/RuleClasses/Method.i"
	@echo "... src/RuleClasses/Method.s"
	@echo "... src/RuleClasses/Program.o"
	@echo "... src/RuleClasses/Program.i"
	@echo "... src/RuleClasses/Program.s"
	@echo "... src/RuleClasses/Statement.o"
	@echo "... src/RuleClasses/Statement.i"
	@echo "... src/RuleClasses/Statement.s"
	@echo "... src/RuleClasses/Type.o"
	@echo "... src/RuleClasses/Type.i"
	@echo "... src/RuleClasses/Type.s"
	@echo "... src/RuleClasses/Var.o"
	@echo "... src/RuleClasses/Var.i"
	@echo "... src/RuleClasses/Var.s"
	@echo "... src/SymbolTable/Symbol.o"
	@echo "... src/SymbolTable/Symbol.i"
	@echo "... src/SymbolTable/Symbol.s"
	@echo "... src/SymbolTable/SymbolTable.o"
	@echo "... src/SymbolTable/SymbolTable.i"
	@echo "... src/SymbolTable/SymbolTable.s"
	@echo "... src/SymbolTable/SymbolTableBuilder.o"
	@echo "... src/SymbolTable/SymbolTableBuilder.i"
	@echo "... src/SymbolTable/SymbolTableBuilder.s"
	@echo "... src/SymbolTable/TypeChecker.o"
	@echo "... src/SymbolTable/TypeChecker.i"
	@echo "... src/SymbolTable/TypeChecker.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

