# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/clion-2018.3.1/bin/cmake/linux/bin/cmake

# The command to remove a file.
RM = /opt/clion-2018.3.1/bin/cmake/linux/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/gregory/Compiler

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/gregory/Compiler

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/opt/clion-2018.3.1/bin/cmake/linux/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/opt/clion-2018.3.1/bin/cmake/linux/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gregory/Compiler/CMakeFiles /home/gregory/Compiler/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/gregory/Compiler/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Compiler

# Build rule for target.
Compiler: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Compiler
.PHONY : Compiler

# fast build rule for target.
Compiler/fast:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/build
.PHONY : Compiler/fast

lexer.o: lexer.cpp.o

.PHONY : lexer.o

# target to build an object file
lexer.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer.cpp.o
.PHONY : lexer.cpp.o

lexer.i: lexer.cpp.i

.PHONY : lexer.i

# target to preprocess a source file
lexer.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer.cpp.i
.PHONY : lexer.cpp.i

lexer.s: lexer.cpp.s

.PHONY : lexer.s

# target to generate assembly for a file
lexer.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/lexer.cpp.s
.PHONY : lexer.cpp.s

parser.o: parser.cpp.o

.PHONY : parser.o

# target to build an object file
parser.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser.cpp.o
.PHONY : parser.cpp.o

parser.i: parser.cpp.i

.PHONY : parser.i

# target to preprocess a source file
parser.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser.cpp.i
.PHONY : parser.cpp.i

parser.s: parser.cpp.s

.PHONY : parser.s

# target to generate assembly for a file
parser.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/parser.cpp.s
.PHONY : parser.cpp.s

src/AST/ASTPrinter.o: src/AST/ASTPrinter.cpp.o

.PHONY : src/AST/ASTPrinter.o

# target to build an object file
src/AST/ASTPrinter.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/AST/ASTPrinter.cpp.o
.PHONY : src/AST/ASTPrinter.cpp.o

src/AST/ASTPrinter.i: src/AST/ASTPrinter.cpp.i

.PHONY : src/AST/ASTPrinter.i

# target to preprocess a source file
src/AST/ASTPrinter.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/AST/ASTPrinter.cpp.i
.PHONY : src/AST/ASTPrinter.cpp.i

src/AST/ASTPrinter.s: src/AST/ASTPrinter.cpp.s

.PHONY : src/AST/ASTPrinter.s

# target to generate assembly for a file
src/AST/ASTPrinter.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/AST/ASTPrinter.cpp.s
.PHONY : src/AST/ASTPrinter.cpp.s

src/ErrorStorage/ErrorStorage.o: src/ErrorStorage/ErrorStorage.cpp.o

.PHONY : src/ErrorStorage/ErrorStorage.o

# target to build an object file
src/ErrorStorage/ErrorStorage.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/ErrorStorage/ErrorStorage.cpp.o
.PHONY : src/ErrorStorage/ErrorStorage.cpp.o

src/ErrorStorage/ErrorStorage.i: src/ErrorStorage/ErrorStorage.cpp.i

.PHONY : src/ErrorStorage/ErrorStorage.i

# target to preprocess a source file
src/ErrorStorage/ErrorStorage.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/ErrorStorage/ErrorStorage.cpp.i
.PHONY : src/ErrorStorage/ErrorStorage.cpp.i

src/ErrorStorage/ErrorStorage.s: src/ErrorStorage/ErrorStorage.cpp.s

.PHONY : src/ErrorStorage/ErrorStorage.s

# target to generate assembly for a file
src/ErrorStorage/ErrorStorage.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/ErrorStorage/ErrorStorage.cpp.s
.PHONY : src/ErrorStorage/ErrorStorage.cpp.s

src/IRT/Expression.o: src/IRT/Expression.cpp.o

.PHONY : src/IRT/Expression.o

# target to build an object file
src/IRT/Expression.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Expression.cpp.o
.PHONY : src/IRT/Expression.cpp.o

src/IRT/Expression.i: src/IRT/Expression.cpp.i

.PHONY : src/IRT/Expression.i

# target to preprocess a source file
src/IRT/Expression.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Expression.cpp.i
.PHONY : src/IRT/Expression.cpp.i

src/IRT/Expression.s: src/IRT/Expression.cpp.s

.PHONY : src/IRT/Expression.s

# target to generate assembly for a file
src/IRT/Expression.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Expression.cpp.s
.PHONY : src/IRT/Expression.cpp.s

src/IRT/Frame.o: src/IRT/Frame.cpp.o

.PHONY : src/IRT/Frame.o

# target to build an object file
src/IRT/Frame.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Frame.cpp.o
.PHONY : src/IRT/Frame.cpp.o

src/IRT/Frame.i: src/IRT/Frame.cpp.i

.PHONY : src/IRT/Frame.i

# target to preprocess a source file
src/IRT/Frame.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Frame.cpp.i
.PHONY : src/IRT/Frame.cpp.i

src/IRT/Frame.s: src/IRT/Frame.cpp.s

.PHONY : src/IRT/Frame.s

# target to generate assembly for a file
src/IRT/Frame.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Frame.cpp.s
.PHONY : src/IRT/Frame.cpp.s

src/IRT/IRTreePrinter.o: src/IRT/IRTreePrinter.cpp.o

.PHONY : src/IRT/IRTreePrinter.o

# target to build an object file
src/IRT/IRTreePrinter.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/IRTreePrinter.cpp.o
.PHONY : src/IRT/IRTreePrinter.cpp.o

src/IRT/IRTreePrinter.i: src/IRT/IRTreePrinter.cpp.i

.PHONY : src/IRT/IRTreePrinter.i

# target to preprocess a source file
src/IRT/IRTreePrinter.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/IRTreePrinter.cpp.i
.PHONY : src/IRT/IRTreePrinter.cpp.i

src/IRT/IRTreePrinter.s: src/IRT/IRTreePrinter.cpp.s

.PHONY : src/IRT/IRTreePrinter.s

# target to generate assembly for a file
src/IRT/IRTreePrinter.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/IRTreePrinter.cpp.s
.PHONY : src/IRT/IRTreePrinter.cpp.s

src/IRT/Label.o: src/IRT/Label.cpp.o

.PHONY : src/IRT/Label.o

# target to build an object file
src/IRT/Label.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Label.cpp.o
.PHONY : src/IRT/Label.cpp.o

src/IRT/Label.i: src/IRT/Label.cpp.i

.PHONY : src/IRT/Label.i

# target to preprocess a source file
src/IRT/Label.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Label.cpp.i
.PHONY : src/IRT/Label.cpp.i

src/IRT/Label.s: src/IRT/Label.cpp.s

.PHONY : src/IRT/Label.s

# target to generate assembly for a file
src/IRT/Label.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Label.cpp.s
.PHONY : src/IRT/Label.cpp.s

src/IRT/Statement.o: src/IRT/Statement.cpp.o

.PHONY : src/IRT/Statement.o

# target to build an object file
src/IRT/Statement.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Statement.cpp.o
.PHONY : src/IRT/Statement.cpp.o

src/IRT/Statement.i: src/IRT/Statement.cpp.i

.PHONY : src/IRT/Statement.i

# target to preprocess a source file
src/IRT/Statement.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Statement.cpp.i
.PHONY : src/IRT/Statement.cpp.i

src/IRT/Statement.s: src/IRT/Statement.cpp.s

.PHONY : src/IRT/Statement.s

# target to generate assembly for a file
src/IRT/Statement.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Statement.cpp.s
.PHONY : src/IRT/Statement.cpp.s

src/IRT/Translator.o: src/IRT/Translator.cpp.o

.PHONY : src/IRT/Translator.o

# target to build an object file
src/IRT/Translator.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Translator.cpp.o
.PHONY : src/IRT/Translator.cpp.o

src/IRT/Translator.i: src/IRT/Translator.cpp.i

.PHONY : src/IRT/Translator.i

# target to preprocess a source file
src/IRT/Translator.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Translator.cpp.i
.PHONY : src/IRT/Translator.cpp.i

src/IRT/Translator.s: src/IRT/Translator.cpp.s

.PHONY : src/IRT/Translator.s

# target to generate assembly for a file
src/IRT/Translator.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/IRT/Translator.cpp.s
.PHONY : src/IRT/Translator.cpp.s

src/Location/Location.o: src/Location/Location.cpp.o

.PHONY : src/Location/Location.o

# target to build an object file
src/Location/Location.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/Location/Location.cpp.o
.PHONY : src/Location/Location.cpp.o

src/Location/Location.i: src/Location/Location.cpp.i

.PHONY : src/Location/Location.i

# target to preprocess a source file
src/Location/Location.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/Location/Location.cpp.i
.PHONY : src/Location/Location.cpp.i

src/Location/Location.s: src/Location/Location.cpp.s

.PHONY : src/Location/Location.s

# target to generate assembly for a file
src/Location/Location.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/Location/Location.cpp.s
.PHONY : src/Location/Location.cpp.s

src/RuleClasses/Arg.o: src/RuleClasses/Arg.cpp.o

.PHONY : src/RuleClasses/Arg.o

# target to build an object file
src/RuleClasses/Arg.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Arg.cpp.o
.PHONY : src/RuleClasses/Arg.cpp.o

src/RuleClasses/Arg.i: src/RuleClasses/Arg.cpp.i

.PHONY : src/RuleClasses/Arg.i

# target to preprocess a source file
src/RuleClasses/Arg.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Arg.cpp.i
.PHONY : src/RuleClasses/Arg.cpp.i

src/RuleClasses/Arg.s: src/RuleClasses/Arg.cpp.s

.PHONY : src/RuleClasses/Arg.s

# target to generate assembly for a file
src/RuleClasses/Arg.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Arg.cpp.s
.PHONY : src/RuleClasses/Arg.cpp.s

src/RuleClasses/Class.o: src/RuleClasses/Class.cpp.o

.PHONY : src/RuleClasses/Class.o

# target to build an object file
src/RuleClasses/Class.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Class.cpp.o
.PHONY : src/RuleClasses/Class.cpp.o

src/RuleClasses/Class.i: src/RuleClasses/Class.cpp.i

.PHONY : src/RuleClasses/Class.i

# target to preprocess a source file
src/RuleClasses/Class.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Class.cpp.i
.PHONY : src/RuleClasses/Class.cpp.i

src/RuleClasses/Class.s: src/RuleClasses/Class.cpp.s

.PHONY : src/RuleClasses/Class.s

# target to generate assembly for a file
src/RuleClasses/Class.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Class.cpp.s
.PHONY : src/RuleClasses/Class.cpp.s

src/RuleClasses/Expression.o: src/RuleClasses/Expression.cpp.o

.PHONY : src/RuleClasses/Expression.o

# target to build an object file
src/RuleClasses/Expression.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Expression.cpp.o
.PHONY : src/RuleClasses/Expression.cpp.o

src/RuleClasses/Expression.i: src/RuleClasses/Expression.cpp.i

.PHONY : src/RuleClasses/Expression.i

# target to preprocess a source file
src/RuleClasses/Expression.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Expression.cpp.i
.PHONY : src/RuleClasses/Expression.cpp.i

src/RuleClasses/Expression.s: src/RuleClasses/Expression.cpp.s

.PHONY : src/RuleClasses/Expression.s

# target to generate assembly for a file
src/RuleClasses/Expression.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Expression.cpp.s
.PHONY : src/RuleClasses/Expression.cpp.s

src/RuleClasses/MainClass.o: src/RuleClasses/MainClass.cpp.o

.PHONY : src/RuleClasses/MainClass.o

# target to build an object file
src/RuleClasses/MainClass.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/MainClass.cpp.o
.PHONY : src/RuleClasses/MainClass.cpp.o

src/RuleClasses/MainClass.i: src/RuleClasses/MainClass.cpp.i

.PHONY : src/RuleClasses/MainClass.i

# target to preprocess a source file
src/RuleClasses/MainClass.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/MainClass.cpp.i
.PHONY : src/RuleClasses/MainClass.cpp.i

src/RuleClasses/MainClass.s: src/RuleClasses/MainClass.cpp.s

.PHONY : src/RuleClasses/MainClass.s

# target to generate assembly for a file
src/RuleClasses/MainClass.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/MainClass.cpp.s
.PHONY : src/RuleClasses/MainClass.cpp.s

src/RuleClasses/Method.o: src/RuleClasses/Method.cpp.o

.PHONY : src/RuleClasses/Method.o

# target to build an object file
src/RuleClasses/Method.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Method.cpp.o
.PHONY : src/RuleClasses/Method.cpp.o

src/RuleClasses/Method.i: src/RuleClasses/Method.cpp.i

.PHONY : src/RuleClasses/Method.i

# target to preprocess a source file
src/RuleClasses/Method.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Method.cpp.i
.PHONY : src/RuleClasses/Method.cpp.i

src/RuleClasses/Method.s: src/RuleClasses/Method.cpp.s

.PHONY : src/RuleClasses/Method.s

# target to generate assembly for a file
src/RuleClasses/Method.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Method.cpp.s
.PHONY : src/RuleClasses/Method.cpp.s

src/RuleClasses/Program.o: src/RuleClasses/Program.cpp.o

.PHONY : src/RuleClasses/Program.o

# target to build an object file
src/RuleClasses/Program.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Program.cpp.o
.PHONY : src/RuleClasses/Program.cpp.o

src/RuleClasses/Program.i: src/RuleClasses/Program.cpp.i

.PHONY : src/RuleClasses/Program.i

# target to preprocess a source file
src/RuleClasses/Program.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Program.cpp.i
.PHONY : src/RuleClasses/Program.cpp.i

src/RuleClasses/Program.s: src/RuleClasses/Program.cpp.s

.PHONY : src/RuleClasses/Program.s

# target to generate assembly for a file
src/RuleClasses/Program.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Program.cpp.s
.PHONY : src/RuleClasses/Program.cpp.s

src/RuleClasses/Statement.o: src/RuleClasses/Statement.cpp.o

.PHONY : src/RuleClasses/Statement.o

# target to build an object file
src/RuleClasses/Statement.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Statement.cpp.o
.PHONY : src/RuleClasses/Statement.cpp.o

src/RuleClasses/Statement.i: src/RuleClasses/Statement.cpp.i

.PHONY : src/RuleClasses/Statement.i

# target to preprocess a source file
src/RuleClasses/Statement.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Statement.cpp.i
.PHONY : src/RuleClasses/Statement.cpp.i

src/RuleClasses/Statement.s: src/RuleClasses/Statement.cpp.s

.PHONY : src/RuleClasses/Statement.s

# target to generate assembly for a file
src/RuleClasses/Statement.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Statement.cpp.s
.PHONY : src/RuleClasses/Statement.cpp.s

src/RuleClasses/Type.o: src/RuleClasses/Type.cpp.o

.PHONY : src/RuleClasses/Type.o

# target to build an object file
src/RuleClasses/Type.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Type.cpp.o
.PHONY : src/RuleClasses/Type.cpp.o

src/RuleClasses/Type.i: src/RuleClasses/Type.cpp.i

.PHONY : src/RuleClasses/Type.i

# target to preprocess a source file
src/RuleClasses/Type.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Type.cpp.i
.PHONY : src/RuleClasses/Type.cpp.i

src/RuleClasses/Type.s: src/RuleClasses/Type.cpp.s

.PHONY : src/RuleClasses/Type.s

# target to generate assembly for a file
src/RuleClasses/Type.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Type.cpp.s
.PHONY : src/RuleClasses/Type.cpp.s

src/RuleClasses/Var.o: src/RuleClasses/Var.cpp.o

.PHONY : src/RuleClasses/Var.o

# target to build an object file
src/RuleClasses/Var.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Var.cpp.o
.PHONY : src/RuleClasses/Var.cpp.o

src/RuleClasses/Var.i: src/RuleClasses/Var.cpp.i

.PHONY : src/RuleClasses/Var.i

# target to preprocess a source file
src/RuleClasses/Var.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Var.cpp.i
.PHONY : src/RuleClasses/Var.cpp.i

src/RuleClasses/Var.s: src/RuleClasses/Var.cpp.s

.PHONY : src/RuleClasses/Var.s

# target to generate assembly for a file
src/RuleClasses/Var.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/RuleClasses/Var.cpp.s
.PHONY : src/RuleClasses/Var.cpp.s

src/SymbolTable/Symbol.o: src/SymbolTable/Symbol.cpp.o

.PHONY : src/SymbolTable/Symbol.o

# target to build an object file
src/SymbolTable/Symbol.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/Symbol.cpp.o
.PHONY : src/SymbolTable/Symbol.cpp.o

src/SymbolTable/Symbol.i: src/SymbolTable/Symbol.cpp.i

.PHONY : src/SymbolTable/Symbol.i

# target to preprocess a source file
src/SymbolTable/Symbol.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/Symbol.cpp.i
.PHONY : src/SymbolTable/Symbol.cpp.i

src/SymbolTable/Symbol.s: src/SymbolTable/Symbol.cpp.s

.PHONY : src/SymbolTable/Symbol.s

# target to generate assembly for a file
src/SymbolTable/Symbol.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/Symbol.cpp.s
.PHONY : src/SymbolTable/Symbol.cpp.s

src/SymbolTable/SymbolTable.o: src/SymbolTable/SymbolTable.cpp.o

.PHONY : src/SymbolTable/SymbolTable.o

# target to build an object file
src/SymbolTable/SymbolTable.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/SymbolTable.cpp.o
.PHONY : src/SymbolTable/SymbolTable.cpp.o

src/SymbolTable/SymbolTable.i: src/SymbolTable/SymbolTable.cpp.i

.PHONY : src/SymbolTable/SymbolTable.i

# target to preprocess a source file
src/SymbolTable/SymbolTable.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/SymbolTable.cpp.i
.PHONY : src/SymbolTable/SymbolTable.cpp.i

src/SymbolTable/SymbolTable.s: src/SymbolTable/SymbolTable.cpp.s

.PHONY : src/SymbolTable/SymbolTable.s

# target to generate assembly for a file
src/SymbolTable/SymbolTable.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/SymbolTable.cpp.s
.PHONY : src/SymbolTable/SymbolTable.cpp.s

src/SymbolTable/SymbolTableBuilder.o: src/SymbolTable/SymbolTableBuilder.cpp.o

.PHONY : src/SymbolTable/SymbolTableBuilder.o

# target to build an object file
src/SymbolTable/SymbolTableBuilder.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/SymbolTableBuilder.cpp.o
.PHONY : src/SymbolTable/SymbolTableBuilder.cpp.o

src/SymbolTable/SymbolTableBuilder.i: src/SymbolTable/SymbolTableBuilder.cpp.i

.PHONY : src/SymbolTable/SymbolTableBuilder.i

# target to preprocess a source file
src/SymbolTable/SymbolTableBuilder.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/SymbolTableBuilder.cpp.i
.PHONY : src/SymbolTable/SymbolTableBuilder.cpp.i

src/SymbolTable/SymbolTableBuilder.s: src/SymbolTable/SymbolTableBuilder.cpp.s

.PHONY : src/SymbolTable/SymbolTableBuilder.s

# target to generate assembly for a file
src/SymbolTable/SymbolTableBuilder.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/SymbolTableBuilder.cpp.s
.PHONY : src/SymbolTable/SymbolTableBuilder.cpp.s

src/SymbolTable/TypeChecker.o: src/SymbolTable/TypeChecker.cpp.o

.PHONY : src/SymbolTable/TypeChecker.o

# target to build an object file
src/SymbolTable/TypeChecker.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/TypeChecker.cpp.o
.PHONY : src/SymbolTable/TypeChecker.cpp.o

src/SymbolTable/TypeChecker.i: src/SymbolTable/TypeChecker.cpp.i

.PHONY : src/SymbolTable/TypeChecker.i

# target to preprocess a source file
src/SymbolTable/TypeChecker.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/TypeChecker.cpp.i
.PHONY : src/SymbolTable/TypeChecker.cpp.i

src/SymbolTable/TypeChecker.s: src/SymbolTable/TypeChecker.cpp.s

.PHONY : src/SymbolTable/TypeChecker.s

# target to generate assembly for a file
src/SymbolTable/TypeChecker.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/SymbolTable/TypeChecker.cpp.s
.PHONY : src/SymbolTable/TypeChecker.cpp.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/Compiler.dir/build.make CMakeFiles/Compiler.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... Compiler"
	@echo "... edit_cache"
	@echo "... lexer.o"
	@echo "... lexer.i"
	@echo "... lexer.s"
	@echo "... parser.o"
	@echo "... parser.i"
	@echo "... parser.s"
	@echo "... src/AST/ASTPrinter.o"
	@echo "... src/AST/ASTPrinter.i"
	@echo "... src/AST/ASTPrinter.s"
	@echo "... src/ErrorStorage/ErrorStorage.o"
	@echo "... src/ErrorStorage/ErrorStorage.i"
	@echo "... src/ErrorStorage/ErrorStorage.s"
	@echo "... src/IRT/Expression.o"
	@echo "... src/IRT/Expression.i"
	@echo "... src/IRT/Expression.s"
	@echo "... src/IRT/Frame.o"
	@echo "... src/IRT/Frame.i"
	@echo "... src/IRT/Frame.s"
	@echo "... src/IRT/IRTreePrinter.o"
	@echo "... src/IRT/IRTreePrinter.i"
	@echo "... src/IRT/IRTreePrinter.s"
	@echo "... src/IRT/Label.o"
	@echo "... src/IRT/Label.i"
	@echo "... src/IRT/Label.s"
	@echo "... src/IRT/Statement.o"
	@echo "... src/IRT/Statement.i"
	@echo "... src/IRT/Statement.s"
	@echo "... src/IRT/Translator.o"
	@echo "... src/IRT/Translator.i"
	@echo "... src/IRT/Translator.s"
	@echo "... src/Location/Location.o"
	@echo "... src/Location/Location.i"
	@echo "... src/Location/Location.s"
	@echo "... src/RuleClasses/Arg.o"
	@echo "... src/RuleClasses/Arg.i"
	@echo "... src/RuleClasses/Arg.s"
	@echo "... src/RuleClasses/Class.o"
	@echo "... src/RuleClasses/Class.i"
	@echo "... src/RuleClasses/Class.s"
	@echo "... src/RuleClasses/Expression.o"
	@echo "... src/RuleClasses/Expression.i"
	@echo "... src/RuleClasses/Expression.s"
	@echo "... src/RuleClasses/MainClass.o"
	@echo "... src/RuleClasses/MainClass.i"
	@echo "... src/RuleClasses/MainClass.s"
	@echo "... src/RuleClasses/Method.o"
	@echo "... src/RuleClasses/Method.i"
	@echo "... src/RuleClasses/Method.s"
	@echo "... src/RuleClasses/Program.o"
	@echo "... src/RuleClasses/Program.i"
	@echo "... src/RuleClasses/Program.s"
	@echo "... src/RuleClasses/Statement.o"
	@echo "... src/RuleClasses/Statement.i"
	@echo "... src/RuleClasses/Statement.s"
	@echo "... src/RuleClasses/Type.o"
	@echo "... src/RuleClasses/Type.i"
	@echo "... src/RuleClasses/Type.s"
	@echo "... src/RuleClasses/Var.o"
	@echo "... src/RuleClasses/Var.i"
	@echo "... src/RuleClasses/Var.s"
	@echo "... src/SymbolTable/Symbol.o"
	@echo "... src/SymbolTable/Symbol.i"
	@echo "... src/SymbolTable/Symbol.s"
	@echo "... src/SymbolTable/SymbolTable.o"
	@echo "... src/SymbolTable/SymbolTable.i"
	@echo "... src/SymbolTable/SymbolTable.s"
	@echo "... src/SymbolTable/SymbolTableBuilder.o"
	@echo "... src/SymbolTable/SymbolTableBuilder.i"
	@echo "... src/SymbolTable/SymbolTableBuilder.s"
	@echo "... src/SymbolTable/TypeChecker.o"
	@echo "... src/SymbolTable/TypeChecker.i"
	@echo "... src/SymbolTable/TypeChecker.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

